CREATE TABLE STUDENTS (
    STUDENT_ID INT,
    NAME STRING,
    DEPARTMENT STRING,
    SEMESTER INT,
    ATTENDANCE_PERCENT FLOAT,
    MARKS FLOAT,
    PLACEMENT_STATUS STRING
);


COPY INTO STUDENTS
FROM @STUDENT_STAGE/student_data.csv
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

SHOW TABLES;


SELECT COUNT(*) AS TOTAL_STUDENTS
FROM STUDENTS;


SELECT DEPARTMENT,
AVG(MARKS) AS AVERAGE_MARKS
FROM STUDENTS 
GROUP BY DEPARTMENT;


SELECT DEPARTMENT, COUNT(*) AS TOTAL
FROM STUDENTS
GROUP BY DEPARTMENT;

SELECT *
FROM STUDENTS
ORDER BY MARKS DESC
LIMIT 5;

SELECT PLACEMENT_STATUS, COUNT(*) AS TOTAL
FROM STUDENTS
GROUP BY PLACEMENT_STATUS;

select max(marks) from students;

SELECT*FROM STUDENTS;



